spring:
  application:
    name: service-consumer
  profiles:
    active: normal
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
  client:
    service-url:
      defaultZone: http://teddy:123456@server1:8100/eureka,http://teddy:123456@server2:8200/eureka
security:
  basic:
    enabled: false
management:
  security:
    enabled: false
feign:
  hystrix:
    enabled: false
logging:
  level:
    root: INFO
    org.springframework.cloud.sleuth: DEBUG