server:
  port: 8200
eureka:
  instance:
    hostname: server2
    instance-id: ${spring.application.name}:${server.port}
  client:
    service-url:
      defaultZone: http://teddy:123456@server1:8100/eureka