server:
  port: 8300
eureka:
  instance:
    hostname: server3
    instance-id: ${spring.application.name}:${server.port}
  client:
    service-url:
      defaultZone: http://teddy:123456@server1:8100/eureka,http://teddy:123456@server2:8200/eureka