spring:
  application:
    name: eureka-server
  profiles:
    active: server1
security:
  basic:
    enabled: true
  user:
    name: teddy
    password: 123456
eureka:
  instance:
    lease-renewal-interval-in-seconds: 5