spring:
  application:
    name: service-gateway
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
  client:
    service-url:
      defaultZone: http://teddy:123456@server1:8100/eureka,http://teddy:123456@server2:8200/eureka
security:
  basic:
    enabled: false
management:
  security:
    enabled: false
server:
  port: 8040
logging:
  level:
    root: INFO
    org.springframework.cloud.sleuth: DEBUG
zuul:
  routes:
    api-a:
      path: /api-user/**
      service-id: service-provider
      sensitive-headers: null
    api-b:
      path: /api-order/**
      service-id: service-consumer